### ISSUE TITLE
[Error in beat annotation]

### ISSUE THREAD

**Issue by SunnyCYC** [fosfrancesco/asap-dataset#1]
Hi, 

Thank you for publishing such useful dataset !
Everything looks great, except that there seems to be some errors in **beat annotation** of **Bach/Fugue/bwv_856/LuoJ01M**.
When listening to the beats/downbeats with Bach/Fugue/bwv_856/LuoJ01M.wav, I found some beats are unreasonably close to downbeats. (starts from 0:14 second)

I'm wondering if this could be an systematic error, or just an single case.
(I only found this one, but I didn't check many.)

What I did is apply librosa.clicks to beats and downbeats (with different click_freq), and listen.
If you need any further information, please let me know.

Thank you!

**Comment by apmcleod** [comment]
Hello,

I'm sorry that I missed this issue before.

I think the problem you are having is that the downbeats are also contained within the beats.

For example, the first few beats after 14 seconds in the file you mentioned are: `14.235416, 14.577082999999998, 14.776563, 15.069792, 15.381771, 15.665104, 15.960764, 16.280556, 16.579687`

The first few downbeats are: `14.577082999999998, 15.381771, 16.280556, ...`

So you see, the downbeats are also in the beats list. You can also verify the timings by looking at the specific  annotations for that file here: https://github.com/fosfrancesco/asap-dataset/blob/master/Bach/Fugue/bwv_856/LuoJ01M_annotations.txt

So, if you create 2 different click tracks at different frequencies and listen to them, you will hear overlapping clicks. Perhaps due to some small difference in how librosa adds clicks of different frequencies, sometimes these may be slightly misaligned.

Do you think this is your issue? You can try to exclude the downbeats from the beats manually before you make the click track to see if that solves the issue. Manually checking the times shows each downbeat to be about 0.2 seconds from the following beat, which is reasonable.

**Comment by apmcleod** [comment]
Hello @SunnyCYC, can you confirm if this was the cause of your issue?

**Comment by SunnyCYC** [comment]
Hi @apmcleod, 

Sorry for my late reply, and thank you for the explanation!
However, what we think unreasonable were the following downbeats and beats:
14.577 (downbeat), 14.776(beat)
18.056 (downbeat), 18.258(beat)
The above spacings were aurally closer than other ones. 

If you would like to have a listen, I also uploaded the wav to google drive:
https://drive.google.com/drive/folders/1MdZaRDgLZvNzRGxSpvIAuF8HWFr69D4g?usp=sharing
I also ploted vlines for the spacing and saved in the folder too. (spacing2.png)

Thank you again for your kind help!

**Comment by apmcleod** [comment]
Hi @SunnyCYC,

Ah, I see it now, thank you! I took a look at the midi as well, and I think I see where the error has come from.

Both cases are during trills in the left hand. You can see the full process of annotation in our paper, but importantly, we take the median of onset times of notes that occur on the beat in the synthesized MIDI. For trills, this includes a note from the trill. Furthermore, since there are only 2 voices at those times, the median value is not able to overcome this trill note outlier.

In the first case (14 seconds), this sounds even slightly worse because the previous downbeat is a bit late due to an error by the performer (the D5 in bar 16 is played late).

For the errors you point out, the correct positions seem to me to be about 0.1 second later than what we have annotated, do you agree?

I would guess that in other cases like this (trills, perhaps combined with a performer error, with fewer than 3 simultaneous voices), you can expect an error up to a maximum of around 0.1 seconds. I don't think this is very common, though. I also wouldn't expect errors much larger than this, because we perform a manual correction step to find any large errors (by looking at the tempo deviation between consecutive beats). These pieces often contain rit. and accel., which can be larger than this deviation, so it fell under our threshold for manual checking.

For beat tracking evaluation, I would expect the majority of such errors would fall within the typical window size for an accepted error (50-70ms), though you can find some (such as these) which do not.

Does this make sense? Will this case be a problem for you?

@fosfrancesco maybe we can fix some of these random errors as people point them out? Are there any other implications of fixing these?

**Comment by fosfrancesco** [comment]
Sure! Sorry, i missed this issue. 
I can work to correct similar minor issues, and maybe create another branch, so people that are already using the dataset get consistent results. 
After a significant number of issues have been fixed we can work to release another version of the dataset.

Thank you @SunnyCYC  for your feedback!

**Comment by SunnyCYC** [comment]
Hi @apmcleod, 

Thank you for the clear explanation!
I agree with you that the correct positions seems to be later than the annotated ones.
Also, these errors seem not common, therefore, not a big problem for our current usage of the dataset.

Thanks again!
